# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
    # Use QEMU session instead of system connection
    libvirt.qemu_use_session = true
    libvirt.uri = 'qemu:///session'
    libvirt.system_uri = 'qemu:///system'

    libvirt.memory = 4096
    libvirt.cpus = 4
  end

  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    # 0. Prequisites for unifios
    apt-get update
    apt-get install -y podman slirp4netns curl jq

    # 1. install unifi os server
    UNIFIOSSERVER_VERSION="4.2.23"
    INSTALLER="/vagrant/assets/unifios-installer-${UNIFIOSSERVER_VERSION}"
    mkdir -p /vagrant/assets
    if [ ! -f "${INSTALLER}" ]; then
        echo "++ Previous UnifiOS Installer ${INSTALLER} not found - downloading"
        wget -o "${INSTALLER}" https://fw-download.ubnt.com/data/unifi-os-server/8b93-linux-x64-4.2.23-158fa00b-6b2c-4cd8-94ea-e92bc4a81369.23-x64
        chmod +x "${INSTALLER}"
    else
        echo "++ Previous UnifiOS Installer ${INSTALLER} found!"
    fi
    echo "y" | ${INSTALLER}

    # 2. enable demo mode for network module
    /vagrant/scripts/demo-mode.sh

    # 3. restart unifi os server
    uosserver stop && uosserver start

    # 4. send setup POST request

    echo "++ Unifi OS Installed, initialising server"
    SETUP_ID=$(curl 'https://localhost:11443/api/setup/start' \
      -X POST -k \
      -H 'Content-Type: application/json' \
      -H 'Origin: https://localhost:11443' \
      --retry 10 --retry-delay 5 --retry-all-errors \
      --data-raw '{"sendTrace":true,"type":"webui"}' | jq -j '.setupId')

    curl 'https://localhost:11443/api/setup' \
        -X POST -k \
        -H 'Content-Type: application/json' \
        -H 'Origin: https://localhost:11443' \
        --data-raw $'{"name":"PulumiTestServer","timezone":"Australia/Sydney","optimizeNetwork":false,"sendDiagnostics":false,"newAccount":true,"advancedSetup":{"mode":"dhcp"},"username":"admin","password":"SimpleIsBetter99\041","country":840,"setupId":"${SETUP_ID}","raid":"raid5"}' \
        > /dev/null

    echo "++ Unifi OS Initialised, login with admin/SimpleIsBetter99!"

  SHELL
end
