# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import pulumi
from enum import Enum

__all__ = [
    'MonitorHealthType',
    'WanAlertThresholdDtoThresholdPolicy',
    'WanMonitorDtoType',
    'WanSlaDtoMonitorHealthType',
]


@pulumi.type_token("unifi-native:wan-slas:MonitorHealthType")
class MonitorHealthType(builtins.str, Enum):
    ALL = "ALL"
    ANY = "ANY"
    MAJORITY = "MAJORITY"
    CUSTOM = "CUSTOM"


@pulumi.type_token("unifi-native:wan-slas:WanAlertThresholdDtoThresholdPolicy")
class WanAlertThresholdDtoThresholdPolicy(builtins.str, Enum):
    ANY = "any"
    ALL = "all"
    ANY_TWO = "any-two"
    LOSS_OR_ALL_OTHERS = "loss-or-all-others"
    LATENCY_OR_ALL_OTHERS = "latency-or-all-others"
    JITTER_OR_ALL_OTHERS = "jitter-or-all-others"
    LOSS_PLUS_ONE = "loss-plus-one"
    LATENCY_PLUS_ONE = "latency-plus-one"
    JITTER_PLUS_ONE = "jitter-plus-one"


@pulumi.type_token("unifi-native:wan-slas:WanMonitorDtoType")
class WanMonitorDtoType(builtins.str, Enum):
    ICMP = "ICMP"
    SPEED_LIMIT = "SPEED_LIMIT"
    DNS = "DNS"


@pulumi.type_token("unifi-native:wan-slas:WanSlaDtoMonitorHealthType")
class WanSlaDtoMonitorHealthType(builtins.str, Enum):
    ALL = "ALL"
    ANY = "ANY"
    MAJORITY = "MAJORITY"
    CUSTOM = "CUSTOM"
