# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'ListDeviceLocalDnsEntriesResult',
    'AwaitableListDeviceLocalDnsEntriesResult',
    'list_device_local_dns_entries',
    'list_device_local_dns_entries_output',
]

@pulumi.output_type
class ListDeviceLocalDnsEntriesResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, list):
            raise TypeError("Expected argument 'items' to be a list")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> Sequence['outputs.LocalDNS']:
        return pulumi.get(self, "items")


class AwaitableListDeviceLocalDnsEntriesResult(ListDeviceLocalDnsEntriesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListDeviceLocalDnsEntriesResult(
            items=self.items)


def list_device_local_dns_entries(site_name: Optional[builtins.str] = None,
                                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListDeviceLocalDnsEntriesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['siteName'] = site_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('unifi-native:devices:listDeviceLocalDnsEntries', __args__, opts=opts, typ=ListDeviceLocalDnsEntriesResult).value

    return AwaitableListDeviceLocalDnsEntriesResult(
        items=pulumi.get(__ret__, 'items'))
def list_device_local_dns_entries_output(site_name: Optional[pulumi.Input[builtins.str]] = None,
                                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListDeviceLocalDnsEntriesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['siteName'] = site_name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('unifi-native:devices:listDeviceLocalDnsEntries', __args__, opts=opts, typ=ListDeviceLocalDnsEntriesResult)
    return __ret__.apply(lambda __response__: ListDeviceLocalDnsEntriesResult(
        items=pulumi.get(__response__, 'items')))
