# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['SettingRadiuArgs', 'SettingRadiu']

@pulumi.input_type
class SettingRadiuArgs:
    def __init__(__self__, *,
                 id: Optional[pulumi.Input[builtins.str]] = None,
                 accounting_enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 acct_port: Optional[pulumi.Input[builtins.int]] = None,
                 attr_hidden: Optional[pulumi.Input[builtins.bool]] = None,
                 attr_hidden_id: Optional[pulumi.Input[builtins.str]] = None,
                 attr_no_delete: Optional[pulumi.Input[builtins.bool]] = None,
                 attr_no_edit: Optional[pulumi.Input[builtins.bool]] = None,
                 auth_port: Optional[pulumi.Input[builtins.int]] = None,
                 configure_whole_network: Optional[pulumi.Input[builtins.bool]] = None,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 interim_update_interval: Optional[pulumi.Input[builtins.int]] = None,
                 key: Optional[pulumi.Input[builtins.str]] = None,
                 site_id: Optional[pulumi.Input[builtins.str]] = None,
                 tunneled_reply: Optional[pulumi.Input[builtins.bool]] = None,
                 x_secret: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a SettingRadiu resource.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if accounting_enabled is not None:
            pulumi.set(__self__, "accounting_enabled", accounting_enabled)
        if acct_port is not None:
            pulumi.set(__self__, "acct_port", acct_port)
        if attr_hidden is not None:
            pulumi.set(__self__, "attr_hidden", attr_hidden)
        if attr_hidden_id is not None:
            pulumi.set(__self__, "attr_hidden_id", attr_hidden_id)
        if attr_no_delete is not None:
            pulumi.set(__self__, "attr_no_delete", attr_no_delete)
        if attr_no_edit is not None:
            pulumi.set(__self__, "attr_no_edit", attr_no_edit)
        if auth_port is not None:
            pulumi.set(__self__, "auth_port", auth_port)
        if configure_whole_network is not None:
            pulumi.set(__self__, "configure_whole_network", configure_whole_network)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if interim_update_interval is not None:
            pulumi.set(__self__, "interim_update_interval", interim_update_interval)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if site_id is not None:
            pulumi.set(__self__, "site_id", site_id)
        if tunneled_reply is not None:
            pulumi.set(__self__, "tunneled_reply", tunneled_reply)
        if x_secret is not None:
            pulumi.set(__self__, "x_secret", x_secret)

    @property
    @pulumi.getter(name="Id")
    def id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "id", value)

    @property
    @pulumi.getter(name="accountingEnabled")
    def accounting_enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "accounting_enabled")

    @accounting_enabled.setter
    def accounting_enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "accounting_enabled", value)

    @property
    @pulumi.getter(name="acctPort")
    def acct_port(self) -> Optional[pulumi.Input[builtins.int]]:
        return pulumi.get(self, "acct_port")

    @acct_port.setter
    def acct_port(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "acct_port", value)

    @property
    @pulumi.getter(name="attrHidden")
    def attr_hidden(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "attr_hidden")

    @attr_hidden.setter
    def attr_hidden(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "attr_hidden", value)

    @property
    @pulumi.getter(name="attrHiddenId")
    def attr_hidden_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "attr_hidden_id")

    @attr_hidden_id.setter
    def attr_hidden_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "attr_hidden_id", value)

    @property
    @pulumi.getter(name="attrNoDelete")
    def attr_no_delete(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "attr_no_delete")

    @attr_no_delete.setter
    def attr_no_delete(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "attr_no_delete", value)

    @property
    @pulumi.getter(name="attrNoEdit")
    def attr_no_edit(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "attr_no_edit")

    @attr_no_edit.setter
    def attr_no_edit(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "attr_no_edit", value)

    @property
    @pulumi.getter(name="authPort")
    def auth_port(self) -> Optional[pulumi.Input[builtins.int]]:
        return pulumi.get(self, "auth_port")

    @auth_port.setter
    def auth_port(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "auth_port", value)

    @property
    @pulumi.getter(name="configureWholeNetwork")
    def configure_whole_network(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "configure_whole_network")

    @configure_whole_network.setter
    def configure_whole_network(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "configure_whole_network", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="interimUpdateInterval")
    def interim_update_interval(self) -> Optional[pulumi.Input[builtins.int]]:
        return pulumi.get(self, "interim_update_interval")

    @interim_update_interval.setter
    def interim_update_interval(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "interim_update_interval", value)

    @property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "key", value)

    @property
    @pulumi.getter(name="siteId")
    def site_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "site_id")

    @site_id.setter
    def site_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "site_id", value)

    @property
    @pulumi.getter(name="tunneledReply")
    def tunneled_reply(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "tunneled_reply")

    @tunneled_reply.setter
    def tunneled_reply(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "tunneled_reply", value)

    @property
    @pulumi.getter(name="xSecret")
    def x_secret(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "x_secret")

    @x_secret.setter
    def x_secret(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "x_secret", value)


@pulumi.type_token("unifi-native:radius:SettingRadiu")
class SettingRadiu(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 id: Optional[pulumi.Input[builtins.str]] = None,
                 accounting_enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 acct_port: Optional[pulumi.Input[builtins.int]] = None,
                 attr_hidden: Optional[pulumi.Input[builtins.bool]] = None,
                 attr_hidden_id: Optional[pulumi.Input[builtins.str]] = None,
                 attr_no_delete: Optional[pulumi.Input[builtins.bool]] = None,
                 attr_no_edit: Optional[pulumi.Input[builtins.bool]] = None,
                 auth_port: Optional[pulumi.Input[builtins.int]] = None,
                 configure_whole_network: Optional[pulumi.Input[builtins.bool]] = None,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 interim_update_interval: Optional[pulumi.Input[builtins.int]] = None,
                 key: Optional[pulumi.Input[builtins.str]] = None,
                 site_id: Optional[pulumi.Input[builtins.str]] = None,
                 tunneled_reply: Optional[pulumi.Input[builtins.bool]] = None,
                 x_secret: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a SettingRadiu resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SettingRadiuArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SettingRadiu resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param SettingRadiuArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SettingRadiuArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 id: Optional[pulumi.Input[builtins.str]] = None,
                 accounting_enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 acct_port: Optional[pulumi.Input[builtins.int]] = None,
                 attr_hidden: Optional[pulumi.Input[builtins.bool]] = None,
                 attr_hidden_id: Optional[pulumi.Input[builtins.str]] = None,
                 attr_no_delete: Optional[pulumi.Input[builtins.bool]] = None,
                 attr_no_edit: Optional[pulumi.Input[builtins.bool]] = None,
                 auth_port: Optional[pulumi.Input[builtins.int]] = None,
                 configure_whole_network: Optional[pulumi.Input[builtins.bool]] = None,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 interim_update_interval: Optional[pulumi.Input[builtins.int]] = None,
                 key: Optional[pulumi.Input[builtins.str]] = None,
                 site_id: Optional[pulumi.Input[builtins.str]] = None,
                 tunneled_reply: Optional[pulumi.Input[builtins.bool]] = None,
                 x_secret: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SettingRadiuArgs.__new__(SettingRadiuArgs)

            __props__.__dict__["id"] = id
            __props__.__dict__["accounting_enabled"] = accounting_enabled
            __props__.__dict__["acct_port"] = acct_port
            __props__.__dict__["attr_hidden"] = attr_hidden
            __props__.__dict__["attr_hidden_id"] = attr_hidden_id
            __props__.__dict__["attr_no_delete"] = attr_no_delete
            __props__.__dict__["attr_no_edit"] = attr_no_edit
            __props__.__dict__["auth_port"] = auth_port
            __props__.__dict__["configure_whole_network"] = configure_whole_network
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["interim_update_interval"] = interim_update_interval
            __props__.__dict__["key"] = key
            __props__.__dict__["site_id"] = site_id
            __props__.__dict__["tunneled_reply"] = tunneled_reply
            __props__.__dict__["x_secret"] = x_secret
        super(SettingRadiu, __self__).__init__(
            'unifi-native:radius:SettingRadiu',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'SettingRadiu':
        """
        Get an existing SettingRadiu resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = SettingRadiuArgs.__new__(SettingRadiuArgs)

        __props__.__dict__["id"] = None
        __props__.__dict__["accounting_enabled"] = None
        __props__.__dict__["acct_port"] = None
        __props__.__dict__["attr_hidden"] = None
        __props__.__dict__["attr_hidden_id"] = None
        __props__.__dict__["attr_no_delete"] = None
        __props__.__dict__["attr_no_edit"] = None
        __props__.__dict__["auth_port"] = None
        __props__.__dict__["configure_whole_network"] = None
        __props__.__dict__["enabled"] = None
        __props__.__dict__["interim_update_interval"] = None
        __props__.__dict__["key"] = None
        __props__.__dict__["site_id"] = None
        __props__.__dict__["tunneled_reply"] = None
        __props__.__dict__["x_secret"] = None
        return SettingRadiu(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="Id")
    def id(self) -> pulumi.Output[Optional[builtins.str]]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="accountingEnabled")
    def accounting_enabled(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "accounting_enabled")

    @property
    @pulumi.getter(name="acctPort")
    def acct_port(self) -> pulumi.Output[Optional[builtins.int]]:
        return pulumi.get(self, "acct_port")

    @property
    @pulumi.getter(name="attrHidden")
    def attr_hidden(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "attr_hidden")

    @property
    @pulumi.getter(name="attrHiddenId")
    def attr_hidden_id(self) -> pulumi.Output[Optional[builtins.str]]:
        return pulumi.get(self, "attr_hidden_id")

    @property
    @pulumi.getter(name="attrNoDelete")
    def attr_no_delete(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "attr_no_delete")

    @property
    @pulumi.getter(name="attrNoEdit")
    def attr_no_edit(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "attr_no_edit")

    @property
    @pulumi.getter(name="authPort")
    def auth_port(self) -> pulumi.Output[Optional[builtins.int]]:
        return pulumi.get(self, "auth_port")

    @property
    @pulumi.getter(name="configureWholeNetwork")
    def configure_whole_network(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "configure_whole_network")

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter(name="interimUpdateInterval")
    def interim_update_interval(self) -> pulumi.Output[Optional[builtins.int]]:
        return pulumi.get(self, "interim_update_interval")

    @property
    @pulumi.getter
    def key(self) -> pulumi.Output[Optional[builtins.str]]:
        return pulumi.get(self, "key")

    @property
    @pulumi.getter(name="siteId")
    def site_id(self) -> pulumi.Output[Optional[builtins.str]]:
        return pulumi.get(self, "site_id")

    @property
    @pulumi.getter(name="tunneledReply")
    def tunneled_reply(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "tunneled_reply")

    @property
    @pulumi.getter(name="xSecret")
    def x_secret(self) -> pulumi.Output[Optional[builtins.str]]:
        return pulumi.get(self, "x_secret")

