# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'AccessPointsGroup',
]

@pulumi.output_type
class AccessPointsGroup(dict):
    def __init__(__self__, *,
                 list_of_device_macs_will_be_ignored_when_updating_default_ap_group: Sequence[builtins.str],
                 name: builtins.str,
                 id: Optional[builtins.str] = None,
                 attr_hidden_id: Optional[builtins.str] = None,
                 attr_no_delete: Optional[builtins.bool] = None,
                 for_wlanconf: Optional[builtins.bool] = None):
        """
        :param builtins.bool for_wlanconf: Mark AP Group as dedicated for a single WLAN Conf (Devices view). It will be hidden from list results by default for backward compatibility, but possible to enable optionally
        """
        pulumi.set(__self__, "list_of_device_macs_will_be_ignored_when_updating_default_ap_group", list_of_device_macs_will_be_ignored_when_updating_default_ap_group)
        pulumi.set(__self__, "name", name)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if attr_hidden_id is not None:
            pulumi.set(__self__, "attr_hidden_id", attr_hidden_id)
        if attr_no_delete is not None:
            pulumi.set(__self__, "attr_no_delete", attr_no_delete)
        if for_wlanconf is not None:
            pulumi.set(__self__, "for_wlanconf", for_wlanconf)

    @property
    @pulumi.getter(name="ListOfDeviceMacsWillBeIgnoredWhenUpdatingDefaultAPGroup")
    def list_of_device_macs_will_be_ignored_when_updating_default_ap_group(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "list_of_device_macs_will_be_ignored_when_updating_default_ap_group")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="Id")
    def id(self) -> Optional[builtins.str]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="attrHiddenId")
    def attr_hidden_id(self) -> Optional[builtins.str]:
        return pulumi.get(self, "attr_hidden_id")

    @property
    @pulumi.getter(name="attrNoDelete")
    def attr_no_delete(self) -> Optional[builtins.bool]:
        return pulumi.get(self, "attr_no_delete")

    @property
    @pulumi.getter(name="forWlanconf")
    def for_wlanconf(self) -> Optional[builtins.bool]:
        """
        Mark AP Group as dedicated for a single WLAN Conf (Devices view). It will be hidden from list results by default for backward compatibility, but possible to enable optionally
        """
        return pulumi.get(self, "for_wlanconf")


