# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

allowInsecure: Optional[bool]
"""
Implicitly trust the Unifi API server's TLS certificate. This is useful for testing, but should not be used in production.
"""

apiHost: Optional[str]
"""
The URL Host name or IP Address for the Unifi API, e.g. 10.1.1.1
"""

apiKey: Optional[str]
"""
The API key for an admin user, generated from the Unifi admin console
"""

siteId: str
"""
The Human readable Stack identifier (e.g. 'notDefault') for the Unifi site to manage. Defaults to 'default'
"""

