# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import pulumi
from enum import Enum

__all__ = [
    'MicroSegmentMemberDtoType',
]


@pulumi.type_token("unifi-native:micro-segment-groups:MicroSegmentMemberDtoType")
class MicroSegmentMemberDtoType(builtins.str, Enum):
    DEVICE = "DEVICE"
