# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'MicroSegmentGroupDto',
    'MicroSegmentMemberDto',
]

@pulumi.output_type
class MicroSegmentGroupDto(dict):
    def __init__(__self__, *,
                 members: Sequence['outputs.MicroSegmentMemberDto'],
                 name: builtins.str,
                 block_internet: Optional[builtins.bool] = None,
                 id: Optional[builtins.str] = None):
        pulumi.set(__self__, "members", members)
        pulumi.set(__self__, "name", name)
        if block_internet is not None:
            pulumi.set(__self__, "block_internet", block_internet)
        if id is not None:
            pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def members(self) -> Sequence['outputs.MicroSegmentMemberDto']:
        return pulumi.get(self, "members")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="blockInternet")
    def block_internet(self) -> Optional[builtins.bool]:
        return pulumi.get(self, "block_internet")

    @property
    @pulumi.getter
    def id(self) -> Optional[builtins.str]:
        return pulumi.get(self, "id")


@pulumi.output_type
class MicroSegmentMemberDto(dict):
    def __init__(__self__, *,
                 id: builtins.str,
                 type: 'MicroSegmentMemberDtoType'):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def type(self) -> 'MicroSegmentMemberDtoType':
        return pulumi.get(self, "type")


