# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import pulumi
from enum import Enum

__all__ = [
    'AlertSettingPreference',
    'SystemLogSettingPreference',
    'SystemLogSettingsSystemLogSettingPreference',
]


@pulumi.type_token("unifi-native:setting:AlertSettingPreference")
class AlertSettingPreference(builtins.str, Enum):
    OFF = "OFF"
    AUTO = "AUTO"
    ON = "ON"


@pulumi.type_token("unifi-native:setting:SystemLogSettingPreference")
class SystemLogSettingPreference(builtins.str, Enum):
    OFF = "OFF"
    AUTO = "AUTO"
    ON = "ON"


@pulumi.type_token("unifi-native:setting:SystemLogSettingsSystemLogSettingPreference")
class SystemLogSettingsSystemLogSettingPreference(builtins.str, Enum):
    OFF = "OFF"
    AUTO = "AUTO"
    ON = "ON"
