# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'MicroSegmentMemberDtoArgs',
    'MicroSegmentMemberDtoArgsDict',
]

MYPY = False

if not MYPY:
    class MicroSegmentMemberDtoArgsDict(TypedDict):
        id: pulumi.Input[builtins.str]
        type: pulumi.Input['MicroSegmentMemberDtoType']
elif False:
    MicroSegmentMemberDtoArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class MicroSegmentMemberDtoArgs:
    def __init__(__self__, *,
                 id: pulumi.Input[builtins.str],
                 type: pulumi.Input['MicroSegmentMemberDtoType']):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def id(self) -> pulumi.Input[builtins.str]:
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "id", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input['MicroSegmentMemberDtoType']:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input['MicroSegmentMemberDtoType']):
        pulumi.set(self, "type", value)


