# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'FingerprintOverrideDto',
]

@pulumi.output_type
class FingerprintOverrideDto(dict):
    def __init__(__self__, *,
                 dev_id_override: Optional[builtins.int] = None,
                 mac: Optional[builtins.str] = None):
        if dev_id_override is not None:
            pulumi.set(__self__, "dev_id_override", dev_id_override)
        if mac is not None:
            pulumi.set(__self__, "mac", mac)

    @property
    @pulumi.getter(name="devIdOverride")
    def dev_id_override(self) -> Optional[builtins.int]:
        return pulumi.get(self, "dev_id_override")

    @property
    @pulumi.getter
    def mac(self) -> Optional[builtins.str]:
        return pulumi.get(self, "mac")


