# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'RadiusProfileDto',
    'RadiusServerDto',
]

@pulumi.output_type
class RadiusProfileDto(dict):
    def __init__(__self__, *,
                 auth_servers: Sequence['outputs.RadiusServerDto'],
                 name: builtins.str,
                 id: Optional[builtins.str] = None,
                 accounting_enabled: Optional[builtins.bool] = None,
                 acct_servers: Optional[Sequence['outputs.RadiusServerDto']] = None,
                 attr_hidden_id: Optional[builtins.str] = None,
                 attr_no_delete: Optional[builtins.bool] = None,
                 attr_no_edit: Optional[builtins.bool] = None,
                 interim_update_enabled: Optional[builtins.bool] = None,
                 interim_update_interval: Optional[builtins.int] = None,
                 vlan_enabled: Optional[builtins.bool] = None,
                 vlan_wlan_mode: Optional['RadiusProfileDtoVlanWlanMode'] = None):
        pulumi.set(__self__, "auth_servers", auth_servers)
        pulumi.set(__self__, "name", name)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if accounting_enabled is not None:
            pulumi.set(__self__, "accounting_enabled", accounting_enabled)
        if acct_servers is not None:
            pulumi.set(__self__, "acct_servers", acct_servers)
        if attr_hidden_id is not None:
            pulumi.set(__self__, "attr_hidden_id", attr_hidden_id)
        if attr_no_delete is not None:
            pulumi.set(__self__, "attr_no_delete", attr_no_delete)
        if attr_no_edit is not None:
            pulumi.set(__self__, "attr_no_edit", attr_no_edit)
        if interim_update_enabled is not None:
            pulumi.set(__self__, "interim_update_enabled", interim_update_enabled)
        if interim_update_interval is not None:
            pulumi.set(__self__, "interim_update_interval", interim_update_interval)
        if vlan_enabled is not None:
            pulumi.set(__self__, "vlan_enabled", vlan_enabled)
        if vlan_wlan_mode is not None:
            pulumi.set(__self__, "vlan_wlan_mode", vlan_wlan_mode)

    @property
    @pulumi.getter(name="authServers")
    def auth_servers(self) -> Sequence['outputs.RadiusServerDto']:
        return pulumi.get(self, "auth_servers")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="Id")
    def id(self) -> Optional[builtins.str]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="accountingEnabled")
    def accounting_enabled(self) -> Optional[builtins.bool]:
        return pulumi.get(self, "accounting_enabled")

    @property
    @pulumi.getter(name="acctServers")
    def acct_servers(self) -> Optional[Sequence['outputs.RadiusServerDto']]:
        return pulumi.get(self, "acct_servers")

    @property
    @pulumi.getter(name="attrHiddenId")
    def attr_hidden_id(self) -> Optional[builtins.str]:
        return pulumi.get(self, "attr_hidden_id")

    @property
    @pulumi.getter(name="attrNoDelete")
    def attr_no_delete(self) -> Optional[builtins.bool]:
        return pulumi.get(self, "attr_no_delete")

    @property
    @pulumi.getter(name="attrNoEdit")
    def attr_no_edit(self) -> Optional[builtins.bool]:
        return pulumi.get(self, "attr_no_edit")

    @property
    @pulumi.getter(name="interimUpdateEnabled")
    def interim_update_enabled(self) -> Optional[builtins.bool]:
        return pulumi.get(self, "interim_update_enabled")

    @property
    @pulumi.getter(name="interimUpdateInterval")
    def interim_update_interval(self) -> Optional[builtins.int]:
        return pulumi.get(self, "interim_update_interval")

    @property
    @pulumi.getter(name="vlanEnabled")
    def vlan_enabled(self) -> Optional[builtins.bool]:
        return pulumi.get(self, "vlan_enabled")

    @property
    @pulumi.getter(name="vlanWlanMode")
    def vlan_wlan_mode(self) -> Optional['RadiusProfileDtoVlanWlanMode']:
        return pulumi.get(self, "vlan_wlan_mode")


@pulumi.output_type
class RadiusServerDto(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "xSecret":
            suggest = "x_secret"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RadiusServerDto. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RadiusServerDto.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RadiusServerDto.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 ip: builtins.str,
                 x_secret: builtins.str,
                 port: Optional[builtins.int] = None):
        pulumi.set(__self__, "ip", ip)
        pulumi.set(__self__, "x_secret", x_secret)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @property
    @pulumi.getter
    def ip(self) -> builtins.str:
        return pulumi.get(self, "ip")

    @property
    @pulumi.getter(name="xSecret")
    def x_secret(self) -> builtins.str:
        return pulumi.get(self, "x_secret")

    @property
    @pulumi.getter
    def port(self) -> Optional[builtins.int]:
        return pulumi.get(self, "port")


