# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import pulumi
from enum import Enum

__all__ = [
    'TrafficIpDtoIpVersion',
    'TrafficIpRangeDtoIpVersion',
    'TrafficRuleDtoAction',
    'TrafficRuleDtoMatchingTarget',
    'TrafficRuleDtoTrafficDirectionUsedForInternetAndLocalNetworkTargets',
    'TrafficRuleScheduleDtoMode',
    'TrafficRuleScheduleDtoRepeatOnDaysItem',
    'TrafficTargetDeviceDtoType',
]


@pulumi.type_token("unifi-native:trafficrule:TrafficIpDtoIpVersion")
class TrafficIpDtoIpVersion(builtins.str, Enum):
    V4 = "v4"
    V6 = "v6"


@pulumi.type_token("unifi-native:trafficrule:TrafficIpRangeDtoIpVersion")
class TrafficIpRangeDtoIpVersion(builtins.str, Enum):
    V4 = "v4"
    V6 = "v6"


@pulumi.type_token("unifi-native:trafficrule:TrafficRuleDtoAction")
class TrafficRuleDtoAction(builtins.str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"


@pulumi.type_token("unifi-native:trafficrule:TrafficRuleDtoMatchingTarget")
class TrafficRuleDtoMatchingTarget(builtins.str, Enum):
    APP = "APP"
    APP_CATEGORY = "APP_CATEGORY"
    DOMAIN = "DOMAIN"
    INTERNET = "INTERNET"
    IP = "IP"
    LOCAL_NETWORK = "LOCAL_NETWORK"
    REGION = "REGION"


@pulumi.type_token("unifi-native:trafficrule:TrafficRuleDtoTrafficDirectionUsedForInternetAndLocalNetworkTargets")
class TrafficRuleDtoTrafficDirectionUsedForInternetAndLocalNetworkTargets(builtins.str, Enum):
    FROM_ = "FROM"
    FROM_AND_TO = "FROM_AND_TO"
    TO = "TO"


@pulumi.type_token("unifi-native:trafficrule:TrafficRuleScheduleDtoMode")
class TrafficRuleScheduleDtoMode(builtins.str, Enum):
    ALWAYS = "ALWAYS"
    EVERY_DAY = "EVERY_DAY"
    EVERY_WEEK = "EVERY_WEEK"
    ONE_TIME_ONLY = "ONE_TIME_ONLY"
    CUSTOM = "CUSTOM"


@pulumi.type_token("unifi-native:trafficrule:TrafficRuleScheduleDtoRepeatOnDaysItem")
class TrafficRuleScheduleDtoRepeatOnDaysItem(builtins.str, Enum):
    SUN = "sun"
    MON = "mon"
    TUE = "tue"
    WED = "wed"
    THU = "thu"
    FRI = "fri"
    SAT = "sat"


@pulumi.type_token("unifi-native:trafficrule:TrafficTargetDeviceDtoType")
class TrafficTargetDeviceDtoType(builtins.str, Enum):
    ALL_CLIENTS = "ALL_CLIENTS"
    CLIENT = "CLIENT"
    NETWORK = "NETWORK"
